from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

from app.services.storage import bootstrap_data_dir, first_existing_data_path, repo_data_path


@dataclass
class FormDoc:
    id: str
    title: str
    filename: str
    description: str
    tags: List[str]


FORMS: List[FormDoc] = [
    FormDoc(
        id="storefront_takeoff",
        title="Storefront Takeoff",
        filename="Storefront-Takeoff.pdf",
        description="Storefront takeoff sheet (stiles/rails, glazing, hardware, closer, frame/system).",
        tags=["storefront", "takeoff", "prl", "aluminum", "glass"],
    ),
    FormDoc(
        id="door_order_single",
        title="Door Order Sheet (Single)",
        filename="Door-Order-Sheet-Single.pdf",
        description="Single door order sheet (size, hinge prep, cutouts, undercut, channels/edges).",
        tags=["door", "order", "single", "steel", "hollow metal"],
    ),
    FormDoc(
        id="door_order_pair",
        title="Door Order Sheet (Pair)",
        filename="Door-Order-Sheet-Pair.pdf",
        description="Pair door order sheet (pair details, astragal, cutouts, net sizes, hinge prep).",
        tags=["door", "order", "pair", "steel", "hollow metal"],
    ),
    FormDoc(
        id="frame_order_single",
        title="Frame Order Sheet (Single)",
        filename="Frame-Order-Sheet-Single.pdf",
        description="Single frame order sheet (throat, jamb depth, strike prep, anchors, silencers).",
        tags=["frame", "order", "single", "hollow metal"],
    ),
    FormDoc(
        id="frame_order_pair",
        title="Frame Order Sheet (Pair)",
        filename="Frame-Order-Sheet-Pair.pdf",
        description="Pair frame order sheet (throat, jamb depth, strikes, anchors, silencers).",
        tags=["frame", "order", "pair", "hollow metal"],
    ),
]


def forms_dir(project_root: str) -> Path:
    # Copy repo-bundled blank takeoff PDFs onto Render disk if a persistent disk is active.
    # This keeps Open/Download working even when /var/data is empty after deploy.
    return bootstrap_data_dir(project_root, "forms")


def list_forms(project_root: str) -> List[Dict]:
    return [
        {
            "id": f.id,
            "title": f.title,
            "description": f.description,
            "tags": f.tags,
            "download_url": f"/forms/download/{f.id}",
            "open_url": f"/forms/download/{f.id}?inline=1",
        }
        for f in FORMS
    ]


def get_form(form_id: str) -> Optional[FormDoc]:
    for f in FORMS:
        if f.id == form_id:
            return f
    return None



def _write_basic_form_pdf(path: Path, form: FormDoc) -> None:
    """Create a lightweight fallback PDF so the Takeoff buttons never 404 on Render.

    Git ignores PDF files in this repo, so bundled PDFs can easily fail to deploy.
    This fallback is intentionally simple and can be replaced later with Jason's exact diagram PDFs.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    c = canvas.Canvas(str(path), pagesize=letter)
    w, h = letter
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, h - 55, form.title)
    c.setFont("Helvetica", 10)
    c.drawString(50, h - 75, form.description or "Priority Door Systems takeoff/order form")
    c.setFont("Helvetica-Bold", 11)
    c.drawString(50, h - 110, "Project / Job #: ____________________________")
    c.drawString(320, h - 110, "Date: ________________")
    c.drawString(50, h - 140, "Customer: __________________________________")
    c.drawString(50, h - 170, "Address: ___________________________________")
    y = h - 215
    fields = [
        "Opening / Location", "Width", "Height", "Handing", "Door Type", "Frame Type",
        "Hardware", "Closer / Operator", "Glass / Infill", "Finish", "Notes"
    ]
    for label in fields:
        c.setFont("Helvetica-Bold", 9)
        c.drawString(55, y + 8, label)
        c.rect(50, y - 18, w - 100, 28, stroke=1, fill=0)
        y -= 36
        if y < 95:
            c.showPage()
            y = h - 70
    c.setFont("Helvetica", 8)
    c.drawString(50, 35, "Fallback form generated by Doorks. Replace with original diagram PDF when available.")
    c.save()

def resolve_form_path(project_root: str, form_id: str) -> Optional[Path]:
    f = get_form(form_id)
    if not f:
        return None
    p = forms_dir(project_root) / f.filename
    if p.exists():
        return p
    repo_p = repo_data_path(project_root, "forms", f.filename)
    if repo_p.exists():
        return repo_p
    # Last-resort fallback: create a simple PDF on the writable data path so Open/Download still works.
    try:
        _write_basic_form_pdf(p, f)
        return p if p.exists() else None
    except Exception:
        return None
